# Every time commits are pushed to master, this workflow
# merges those commits into nightly. The idea is that commits
# against the plugin's stable branch (master) should always
# be reflected on its bleeding-edge branch (nightly) as well.
#
# If there is a merge commit, it is associated with
# "github-actions[bot]", which is not a real user account.
#
# Assumptions:
#  * The default branch is master, not main.
#  * GitHub Actions have been given access to read & write repository
#    contents (from repository settings).
#  * Write access is sufficient for pushing to nightly. Requiring
#    PRs for nightly would break this workflow.

name: Merge master into nightly

on:
  push:
    branches: [ master ]

jobs:
  merge-to-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # all branches and tags
      - name: Merge
        run: |
          git checkout nightly
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git merge master
      - name: Push
        run: |
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}
          git push origin nightly
